realestate/home/urls.py
from django.urls import path
from . import views


app_name= 'home'

urlpatterns = [
    path('', views.home, name='home')
    
]

realestate/properties/urls.py
from django.urls import path
from . import views



app_name= 'properties'

urlpatterns = [
    path('', views.properties, name="propertiesView"),
    path('<int:homes_id>', views.propertie_detail, name='detail')
]

realestate/realestate/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

realestate/home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

realestate/properties/models.py
from django.db import models
from django.db.models.fields import TextField
from django.utils import timezone
# Create your models here.
class Homes(models.Model):
    house_name= models.CharField(max_length=50)
    address = models.TextField(max_length=255)
    date_added = models.DateTimeField(default=timezone.now)
    description = models.TextField()

    price = models.IntegerField()
    bedroom_amount = models.IntegerField()
    bathroom_amount = models.IntegerField()
    house_floor = models.IntegerField()
    garage_amount = models.IntegerField()
    square_feet = models.IntegerField()

    house_image = models.ImageField(upload_to = 'main_images')
    secondary_image = models.ImageField(upload_to = 'secondary_images')

realestate/home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

realestate/properties/views.py
from django.shortcuts import get_object_or_404, render
from .models import Homes

# Create your views here.
def properties(request):
    homes = Homes.objects.all()
    return render(request, 'properties/properties.html', {'homes' : homes})

def propertie_detail(request, homes_id):
    homes = get_object_or_404(Homes, pk = homes_id)
    return render(request, 'properties/detail.html', {'home': homes})

realestate/realestate/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

realestate/home/templates/home.html
{% extends 'base.html' %}
{%load static%}

{% block content %}

<div class="hero-container">
    <div class="hero-text-container">
        <hr>
        <p class="small-text">Best Estate Company</p>
        <h1 class="hero-title">Let Us Get you Your 
            new Home</h1>
        <p class="hero-text">Here we will help you find your new home that you can
            be proud of. With our contacts all over we will find a place
            right on time</p>
    </div>
    <div class="hero-image">
        <img src="{% static 'images/hero.jpg' %}" alt="house">
    </div>
</div>

<section class="section1">
    <div class="container">
        <div class="grey-box"></div>
        <div class="big-image"> <img src="{% static 'images/section1-b.jpg'%}" alt="luxury home"></div>
        <div class="small-image"> <img src="{% static 'images/section1-s.jpg'%}" alt="wooden lucury home"></div>
        <div class="section1-text">
            <h2 class="section-title">Top Real Estate services</h2>
            <p class="section-p">Our homes are build by the best architecturres
                Sculpted by the best builders
                and is sure to please all your needs</p>
        </div>
    </div>
</section>

<section class="section2">
    <img src="{% static 'images/section2.jpg' %}" alt="" class="section2-image">
    <div class="section2-text">
        <p class="side-text">Sleek</p>
        <p class="side-text">Stable</p>
        <p class="side-text">and Reliable</p>
    </div>
</section>

<section class="section3">
    <div class="grid">
        <div class="img-1">
            <div class="grid-text">
                <h1 class="section-title">Durable Structures</h2>
                <p class="section-p">we have designed and constructed over 900 projects
                    from coast to coast, and have preformed extensive 
                    retrofitting of existing structures
                </p>
            </div>
            <img src="{% static 'images/grid-1.jpg'%}" alt="">
        </div>
        <div class="img-2">
            <img src="{% static 'images/grid-2.jpg'%}" alt="">
        </div>
        <div class="img-3">
            <img src="{% static 'images/grid-3.jpg'%}" alt="">
        </div>

    </div>
</section>


<section class="section4">
    <div class="flex">
        <div class="image-container ">
            <img src="{% static 'images/section4-b.jpg'%}" alt="" class="section4-imageb">
        </div>
        <div class="image-container ">
            <div class="text-container">
                <h2 class="section-title">About us</h2>
                <p class="section-p">our team is reliable and will be 
                    there to help you at all times.
                    we are here to provide you with the 
                    best service</p>
            </div>
            <img src="{% static 'images/section4-s.jpg'%}" alt="" >
        </div>
    </div>
</section>

<footer class= "footer">

</footer>







{% endblock %}

realestate/properties/templates/properties/detail.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'properties/details.css' %}">
</head>
<body>
    <div class="nav-top">
        <a href="{%url 'properties:propertiesView'%}"><img class="icon-size" src="{%static 'FixedImages/DetailsPage/arrow.png'%}" alt=""></a>
    </div>
    
    <div class="hero-detail">
        <div class="propertie-detail-text">
            <h1 class="detail-title">{{home.house_name}}</h1>
            <div class="grid-detail">
                <div class="bedroom">
                    <div class="top">
                        <p class="number">{{home.bedroom_amount}}</p>
                        <img src="{%static 'FixedImages/DetailsPage/bed.png'%}" alt="" class="icon">
                    </div>
                    <p class="bottom-text">Bedrooms</p>
                </div>

                <div class="bathroom">
                    <div class="top">
                        <p class="number">{{home.bathroom_amount}}</p>
                        <img src="{%static 'FixedImages/DetailsPage/shower.png'%}" alt="" class="icon">
                    </div>
                    <p class="bottom-text">Bathrooms</p>
                </div>

                <div class="levels">
                    <div class="top">
                        <p class="number">{{home.house_floor}}</p>
                        <img src="{%static 'FixedImages/DetailsPage/level.png'%}" alt="" class="icon">
                    </div>
                    <p class="bottom-text">Levels</p>
                </div>

                <div class="garage">
                    <div class="top">
                        <p class="number">{{home.garage_amount}}</p>
                        <img src="{%static 'FixedImages/DetailsPage/garage.png'%}" alt="" class="icon">
                    </div>
                    <p class="bottom-text">Garage</p>
                </div>
            </div>
        </div>
        <div class="detail-image">
            <img src="{{home.house_image.url}}" alt="" class="detail-hero-image">
        </div>
    </div>

    <div class="detail-section">
        <div class="text-flex">
            <div class="first-flex">
                <p class="start">Starting at</p>
                <p class="detail-price">${{home.price}}</p>
                <p class="detail-sqr">{{home.square_feet}} sq ft</p>
            </div>

            <div class="middle-flex">
                <p class="detail-description">{{home.description}}</p>
            </div>

            <div class="last-flex">
                <h2 class="flex-detail-title">{{home.house_name}}</h2>
            </div>
        </div>
    </div>

    <div class="bottom-detail-container">
        <div class="image-detail-bottom-container">
            <img class="image-size" src="{{home.secondary_image.url}}" alt="inner house">
        </div>

        <div class="bottom-detail-text">
            <h2 class="bottom-title">Contact</h2>
            <div class="contact">
                <img src="{%static 'FixedImages/DetailsPage/email.png'%}" alt="" class="contact-image">
                <p class="contact-text">Example@gmail.com</p>
            </div>
            <div class="contact">
                <img src="{%static 'FixedImages/DetailsPage/phone.png'%}" alt="" class="contact-image">
                <p class="contact-text">#090900909</p>
            </div>
        </div>
    </div>
    <footer class= "footer">

    </footer>

</body>
</html>

realestate/properties/templates/properties/properties.html
{% extends 'base.html' %}

{%load static%}

{% block content %}



    
        <div class="square"></div>
        <div class="page-title">
            <h1 class="properties-headline">Properties
                <hr class="headline">
            </h1>
        
        </div>
        
        
        <div class="main-propertie-content">
            <div class="content-side">
                <div class="content-grid">
                    {% for home in homes %}
                       <a class="link-card" href="{%url 'properties:detail' home.id%}">
                           <div class="propertie-card">
                               <div class="propertie-image">
                                   <img src="{{home.house_image.url}}" alt="home" class="propertie-img">
                               </div>
                               <div class="propertie-text-container">
                                   <hr class="BegLine">
                                   <h2 class="propertie-name">{{home.house_name}}</h2>
                                   <p class="propertie-location">{{home.address}}</p>
                                   <p class="propertie-price">$ {{home.price}}<span>/Month</span></p>
                               </div>
                           </div>
                       </a>
                    {% endfor %}
                </div>
            </div>
            <div class="image-side">
                <img src="{% static 'FixedImages/PropertiesPage/side.jpg'%}" alt="Chandeliers" class="side-img">
            </div>
        </div>
    

   
    
    

{% endblock  %}

realestate/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'properties/properties.css'%}">
    <title>Real estate company</title>
</head>
<body class="h">
    <div class="body">
        <div class="nav">
            <a href="{%url 'properties:propertiesView'%}">
                <div class="asset">
                    <div class="hover">
                        <img src="{%static 'FixedImages/basefiles/houses.png'%}" alt="" class="icon-base">
                    </div>
                    <div class="inner-hover"></div>
                </div>
            </a>
            <a href="{%url 'home:home'%}">
                <div class="asset">
                    <div class="hover">
                    <img src="{%static 'FixedImages/basefiles/home.png'%}" alt="" class="icon-base">
                    </div>
                    <div class="inner-hover"></div>
                </div>
            </a>
        </div>
        {% block content %}{% endblock  %}
    </div>
</body>
</html>